# Generated by Django 3.0.3 on 2020-08-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='link',
            field=models.URLField(max_length=250),
        ),
    ]
