# Generated by Django 3.0.3 on 2020-08-22 16:48

from django.db import migrations, models
import embed_video.fields
import hotsite.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotsite', '0002_auto_20200819_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast', models.ImageField(blank=True, null=True, upload_to=hotsite.models.get_image_path)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Storie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storie', embed_video.fields.EmbedVideoField()),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='link',
        ),
    ]
